import React, { useEffect, useMemo, useState } from "react";
import { BookOpen, LockKeyhole, PlayCircle, X } from "lucide-react";
import PageHeader from "@/components/PageHeader";
import StatusPanel from "@/components/StatusPanel";
import { base44 } from "@/api/base44Client";
import { invokeAppFunction } from "@/services/marketService";
import { usePreferences } from "@/lib/preferences";

function newInstance() { return crypto.randomUUID(); }
export default function Courses() {
  const { isArabic } = usePreferences(); const authenticated = Boolean(localStorage.getItem("smart_investor_session_id"));
  const [state, setState] = useState({ loading: true, courses: [], lessons: {}, error: "" }); const [player, setPlayer] = useState(null); const instance = useMemo(newInstance, []);
  useEffect(() => { (async () => { try { const data = authenticated ? await invokeAppFunction("trainingContent", { action: "list" }) : (await base44.functions.invoke("trainingContent", { action: "public_list" })).data; setState({ loading: false, courses: data.courses || [], lessons: data.lessons || {}, error: "" }); } catch (error) { setState({ loading: false, courses: [], lessons: {}, error: error?.response?.data?.error || error.message }); } })(); }, [authenticated]);
  async function play(lesson, course) { try { const result = authenticated ? await invokeAppFunction("trainingContent", { action: "playback", lesson_id: lesson.id, player_instance_id: instance }) : (await base44.functions.invoke("trainingContent", { action: "public_playback", lesson_id: lesson.id })).data; setPlayer({ ...result, lesson, course }); } catch (error) { setState((current) => ({ ...current, error: error?.response?.data?.error || error.message })); } }
  async function close() { if (player?.lease_id) { try { await invokeAppFunction("trainingContent", { action: "release_playback", lease_id: player.lease_id }); } catch { /* lease expires automatically */ } } setPlayer(null); }
  return <div className="min-h-screen bg-slate-50 dark:bg-[#08111f]"><PageHeader title={isArabic ? "الدورات والتدريب" : "Courses & training"} description={isArabic ? "محتوى عملي يساعدك على الاستفادة من المستثمر الذكي بثقة ووضوح." : "Practical learning that helps you use Smart Investor with clarity and confidence."} />
    <div className="mx-auto max-w-6xl px-4 pb-12">{state.loading ? <StatusPanel loading /> : <div className="grid gap-5 md:grid-cols-2">{state.courses.map((course) => <article key={course.id} className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-[#0d192a]"><div className="flex items-center justify-between"><BookOpen className="text-sky-500" /><span className="flex items-center gap-1 text-xs text-slate-500">{course.visibility === "market" && <LockKeyhole size={13} />}{course.market_code || (isArabic ? "متاح للجميع" : "Public")}</span></div><h2 className="mt-4 text-xl font-black">{isArabic ? course.title_ar : course.title_en}</h2><p className="mt-2 text-sm leading-7 text-slate-500">{isArabic ? course.description_ar : course.description_en}</p><div className="mt-4 space-y-2">{(state.lessons[course.id] || []).filter((lesson) => lesson.published).map((lesson) => <button key={lesson.id} className="secondary-button w-full justify-start" onClick={() => play(lesson, course)}><PlayCircle size={16} />{isArabic ? lesson.title_ar : lesson.title_en}</button>)}</div></article>)}{!state.courses.length && <StatusPanel title={isArabic ? "لا توجد دورات منشورة حالياً" : "No published courses yet"} />}</div>}</div>
    {player && <div className="fixed inset-0 z-[120] grid place-items-center bg-black/90 p-3"><div className="relative w-full max-w-5xl"><button className="absolute -top-10 end-0 text-white" onClick={close}><X /></button><div className="relative aspect-video overflow-hidden rounded-2xl bg-black"><iframe title={isArabic ? player.lesson.title_ar : player.lesson.title_en} className="h-full w-full" src={player.playback.url} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen /><div className="pointer-events-none absolute inset-0 grid place-items-center overflow-hidden opacity-15"><span className="rotate-[-18deg] text-sm font-bold text-white">{player.watermark}</span></div></div></div></div>}
    {state.error && <div className="fixed bottom-4 end-4 z-[130] max-w-sm rounded-xl bg-red-950 p-4 text-sm text-red-200">{state.error}</div>}
  </div>;
}
