import React, { useEffect, useState } from "react";
import { ExternalLink, Send } from "lucide-react";
import PageHeader from "@/components/PageHeader";
import StatusPanel from "@/components/StatusPanel";
import { invokeAppFunction } from "@/services/marketService";
import { usePreferences } from "@/lib/preferences";

const markets = [["SA_MAIN", "السوق السعودية", "Saudi Market"], ["US_OPTIONS", "عقود الخيارات الأمريكية", "U.S. Options"], ["US_BENCHMARKS", "المؤشرات والصناديق الأمريكية", "U.S. Indices & ETFs"]];
export default function MarketApplications() {
  const { isArabic } = usePreferences(); const [data, setData] = useState({ applications: [], platforms: [] }); const [market, setMarket] = useState("SA_MAIN"); const [platformId, setPlatformId] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  async function load() { try { const result = await invokeAppFunction("customerAccess", { action: "list" }); setData(result); } catch (issue) { setError(issue?.response?.data?.error || issue.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  const platforms = data.platforms.filter((item) => item.supported_market_codes?.includes(market)); const selected = platforms.find((item) => item.id === platformId);
  useEffect(() => { if (!platforms.some((item) => item.id === platformId)) setPlatformId(platforms[0]?.id || ""); }, [market, data.platforms]);
  async function submit(event) { event.preventDefault(); setError(""); try { await invokeAppFunction("customerAccess", { action: "apply", market_code: market, trading_platform_id: platformId }); await load(); } catch (issue) { setError(issue?.response?.data?.error || issue.message); } }
  return <><PageHeader title={isArabic ? "طلبات الأسواق" : "Market applications"} description={isArabic ? "كل تسجيل في منصة تداول يفتح سوقاً واحداً فقط بعد موافقة المالك." : "Each trading-platform registration unlocks one market only after owner approval."} /><div className="mx-auto grid max-w-5xl gap-5 px-4 pb-10 md:grid-cols-2"><section className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-[#0d192a]"><h2 className="font-black">{isArabic ? "طلب سوق إضافي" : "Request another market"}</h2><form className="mt-4 space-y-3" onSubmit={submit}><select className="form-input w-full" value={market} onChange={(event) => setMarket(event.target.value)}>{markets.map(([code, ar, en]) => <option key={code} value={code}>{isArabic ? ar : en}</option>)}</select><select className="form-input w-full" required value={platformId} onChange={(event) => setPlatformId(event.target.value)}>{platforms.map((item) => <option key={item.id} value={item.id}>{isArabic ? item.name_ar : item.name_en}</option>)}</select>{selected?.referral_url && <a className="flex items-center gap-2 text-sm font-bold text-sky-600 underline" href={selected.referral_url} target="_blank" rel="noreferrer"><ExternalLink size={14} />{isArabic ? "التسجيل في منصة التداول" : "Register with trading platform"}</a>}<button className="primary-button" disabled={!platformId}><Send size={15} />{isArabic ? "إرسال الطلب" : "Submit request"}</button></form></section><section className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-[#0d192a]"><h2 className="font-black">{isArabic ? "طلباتي" : "My applications"}</h2>{loading ? <StatusPanel loading /> : <div className="mt-4 space-y-3">{data.applications.map((item) => <article key={item.id} className="rounded-xl border border-slate-200 p-3 text-sm dark:border-slate-700"><b>{item.unique_reference}</b><p className="mt-1 text-slate-500">{item.market_code} · {item.status}</p></article>)}</div>}</section></div>{error && <div className="fixed bottom-4 end-4 rounded-xl bg-red-950 p-4 text-sm text-red-200">{error}</div>}</>;
}
